name: nyxx_sharding
description: External sharding for nyxx.
version: 2.0.0
homepage: https://github.com/nyxx-discord/nyxx_sharding
repository: https://github.com/nyxx-discord/nyxx_sharding
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/nyxx-discord/nyxx_sharding/issues

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  args: ^2.3.0
  http: ^0.13.4
  logging: ^1.0.2
  nyxx: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  nyxx-sharding: sharding
